"""Initial PostgreSQL migration with UUID

Revision ID: 3658a5cc3b50
Revises: 
Create Date: 2025-11-11 16:57:42.982631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3658a5cc3b50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offering_activities',
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.offering_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offering_id', 'activity_id')
    )
    op.drop_constraint(op.f('activities_offering_id_fkey'), 'activities', type_='foreignkey')
    op.drop_column('activities', 'offering_id')
    op.drop_column('activities', 'brand')
    op.drop_column('activities', 'sequence')
    op.drop_column('activities', 'supported_product')
    op.drop_column('activities', 'is_mandatory')
    op.drop_column('offerings', 'activities')
    op.alter_column('pricing_details', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('pricing_details', 'sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.create_unique_constraint('unique_country_role_band', 'pricing_details', ['country', 'role', 'band'])
    op.alter_column('staffing_details', 'activity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('staffing_details', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('staffing_details', 'role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('staffing_details', 'band',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('staffing_details', 'hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staffing_details', 'hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('staffing_details', 'band',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('staffing_details', 'role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('staffing_details', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('staffing_details', 'activity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('unique_country_role_band', 'pricing_details', type_='unique')
    op.alter_column('pricing_details', 'sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('pricing_details', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.add_column('offerings', sa.Column('activities', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('is_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('supported_product', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('offering_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('activities_offering_id_fkey'), 'activities', 'offerings', ['offering_id'], ['offering_id'])
    op.drop_table('offering_activities')
    # ### end Alembic commands ###
