"""Columns Corrections-2

Revision ID: 56867c151c16
Revises: f5db8b2a4c40
Create Date: 2025-11-12 12:07:38.380626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56867c151c16'
down_revision: Union[str, Sequence[str], None] = 'f5db8b2a4c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wbs',
    sa.Column('wbs_id', sa.UUID(), nullable=False),
    sa.Column('wbs_description', sa.String(length=255), nullable=False),
    sa.Column('wbs_weeks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('wbs_id')
    )
    op.create_table('activity_wbs',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('wbs_id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs.wbs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'wbs_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_wbs')
    op.drop_table('wbs')
    # ### end Alembic commands ###
