"""Columns Corrections

Revision ID: 5d2b2f87b02e
Revises: c171b0e597a8
Create Date: 2025-11-12 11:50:28.136013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2b2f87b02e'
down_revision: Union[str, Sequence[str], None] = 'c171b0e597a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('brand', sa.String(length=150), nullable=True))
    op.add_column('activities', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('offerings', sa.Column('sale_price', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offerings', 'sale_price')
    op.drop_column('activities', 'product_name')
    op.drop_column('activities', 'brand')
    # ### end Alembic commands ###
