"""add cascade deletes to all relationships

Revision ID: 70de9e06c549
Revises: f4de754dfe06
Create Date: 2025-11-16 14:37:45.062936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70de9e06c549'
down_revision: Union[str, Sequence[str], None] = 'f4de754dfe06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('offerings_product_id_fkey'), 'offerings', type_='foreignkey')
    op.create_foreign_key(None, 'offerings', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_brand_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['brand_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('staffing_details_activity_id_fkey'), 'staffing_details', type_='foreignkey')
    op.create_foreign_key(None, 'staffing_details', 'activities', ['activity_id'], ['activity_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staffing_details', type_='foreignkey')
    op.create_foreign_key(op.f('staffing_details_activity_id_fkey'), 'staffing_details', 'activities', ['activity_id'], ['activity_id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_brand_id_fkey'), 'products', 'brands', ['brand_id'], ['brand_id'])
    op.drop_constraint(None, 'offerings', type_='foreignkey')
    op.create_foreign_key(op.f('offerings_product_id_fkey'), 'offerings', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
