"""Removed offering_id in staffing_details

Revision ID: c171b0e597a8
Revises: 724c6fd3ec5b
Create Date: 2025-11-11 18:21:29.858662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c171b0e597a8'
down_revision: Union[str, Sequence[str], None] = '724c6fd3ec5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('staffing_details_offering_id_fkey'), 'staffing_details', type_='foreignkey')
    op.drop_column('staffing_details', 'offering_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffing_details', sa.Column('offering_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('staffing_details_offering_id_fkey'), 'staffing_details', 'offerings', ['offering_id'], ['offering_id'])
    # ### end Alembic commands ###
