"""Columns Corrections-1

Revision ID: f5db8b2a4c40
Revises: 5d2b2f87b02e
Create Date: 2025-11-12 12:02:02.101901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5db8b2a4c40'
down_revision: Union[str, Sequence[str], None] = '5d2b2f87b02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
